"""
vulngen/stage5_validation.py
-----------------------------
Stage 5 — Real-world validation on AI-tool generated snippets.

Collects and analyses 1,600 snippets from:
  - GitHub Copilot   (800 snippets)
  - CodeWhisperer    (400 snippets)
  - Cursor           (400 snippets)

Repositories are identified via GitHub Search API using
AI-suggestion markers in commit messages and file metadata.

Paper reference: Section V-C, Table VI

Author: Anuansh Tiwari <anuanshtiwari191@gmail.com>
"""

from __future__ import annotations

import os
import re
import time
from dataclasses import dataclass, field
from typing import List, Optional

from loguru import logger

try:
    from github import Github, GithubException
    _GITHUB_AVAILABLE = True
except ImportError:
    _GITHUB_AVAILABLE = False

from vulngen.stage4_analysis import SASTEnsemble
from vulngen.stage6_scoring import CWEScorer


# ---------------------------------------------------------------------------
# Search queries that identify AI-tool generated code in public repos
# ---------------------------------------------------------------------------

TOOL_SEARCH_QUERIES = {
    "copilot": [
        "copilot suggestion",
        "github copilot generated",
        "co-authored-by: GitHub Copilot",
    ],
    "codewhisperer": [
        "Amazon CodeWhisperer",
        "codewhisperer suggestion",
        "generated by CodeWhisperer",
    ],
    "cursor": [
        "cursor ai generated",
        "generated with cursor",
        "cursor composer",
    ],
}

LANGUAGE_EXTENSIONS = {
    "python": [".py"],
    "javascript": [".js", ".ts"],
    "java": [".java"],
    "cpp": [".cpp", ".cc", ".cxx", ".c"],
}

SNIPPET_TARGETS = {
    "copilot": 800,
    "codewhisperer": 400,
    "cursor": 400,
}


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class WildSnippet:
    snippet_id: str
    source_tool: str          # copilot / codewhisperer / cursor
    language: str
    code: str
    repo_full_name: str
    file_path: str
    commit_sha: str
    is_vulnerable: bool = False
    cwe_ids: List[str] = field(default_factory=list)
    cvss_score: Optional[float] = None
    sast_findings: List[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return self.__dict__.copy()


# ---------------------------------------------------------------------------
# Validator
# ---------------------------------------------------------------------------

class RealWorldValidator:
    """
    Collects AI-generated snippets from GitHub and analyses them
    through the same SAST ensemble as the controlled study.

    Requires: GITHUB_TOKEN environment variable.
    """

    def __init__(self, snippet_count: int = 1600):
        self.snippet_count = snippet_count
        self.sast = SASTEnsemble()
        self.scorer = CWEScorer()

        if not _GITHUB_AVAILABLE:
            raise ImportError(
                "PyGithub not installed. Run: pip install PyGithub"
            )
        token = os.environ.get("GITHUB_TOKEN", "")
        if not token:
            raise EnvironmentError(
                "GITHUB_TOKEN environment variable not set.\n"
                "Create a token at https://github.com/settings/tokens"
            )
        self._gh = Github(token)

    # ------------------------------------------------------------------
    # Main entry
    # ------------------------------------------------------------------

    def collect_and_analyse(self) -> List[dict]:
        """Collect snippets from all three tools, analyse, and return records."""
        all_records: List[dict] = []
        for tool, target in SNIPPET_TARGETS.items():
            logger.info(f"Collecting {target} snippets from {tool}…")
            snippets = self._collect_tool_snippets(tool, target)
            logger.info(f"  Collected {len(snippets)} snippets. Running SAST…")
            for snippet in snippets:
                findings = self.sast.analyse(snippet.code, snippet.language)
                snippet.is_vulnerable = self.sast.majority_vote(findings)
                snippet.cwe_ids = self.sast.extract_cwes(findings)
                snippet.sast_findings = findings
                if snippet.is_vulnerable:
                    scored = self.scorer.score(
                        {"cwe_ids": snippet.cwe_ids, "generated_code": snippet.code}
                    )
                    snippet.cvss_score = scored.get("cvss_score")
                all_records.append(snippet.to_dict())

        vr = sum(r["is_vulnerable"] for r in all_records) / max(len(all_records), 1)
        logger.info(
            f"Real-world validation complete. "
            f"Total: {len(all_records)} snippets, VR: {vr:.1%}"
        )
        return all_records

    # ------------------------------------------------------------------
    # GitHub collection helpers
    # ------------------------------------------------------------------

    def _collect_tool_snippets(
        self, tool: str, target: int
    ) -> List[WildSnippet]:
        snippets: List[WildSnippet] = []
        queries = TOOL_SEARCH_QUERIES[tool]

        for query in queries:
            if len(snippets) >= target:
                break
            repos = self._search_repos(query)
            for repo in repos:
                if len(snippets) >= target:
                    break
                batch = self._extract_snippets_from_repo(repo, tool)
                snippets.extend(batch)
                time.sleep(0.5)   # GitHub API rate limiting

        return snippets[:target]

    def _search_repos(self, query: str, max_repos: int = 50) -> list:
        try:
            results = self._gh.search_repositories(
                query=f"{query} language:Python stars:>5",
                sort="updated",
            )
            repos = []
            for repo in results:
                repos.append(repo)
                if len(repos) >= max_repos:
                    break
            return repos
        except GithubException as exc:
            logger.warning(f"GitHub search error: {exc}")
            return []

    def _extract_snippets_from_repo(
        self, repo, tool: str, max_per_repo: int = 5
    ) -> List[WildSnippet]:
        snippets: List[WildSnippet] = []
        try:
            contents = repo.get_contents("")
            files = [c for c in contents if c.type == "file"]
            for f in files[:max_per_repo]:
                lang = self._detect_language(f.path)
                if not lang:
                    continue
                try:
                    code = f.decoded_content.decode("utf-8", errors="replace")
                    functions = self._extract_functions(code, lang)
                    for i, func in enumerate(functions[:2]):
                        sid = f"{tool}_{repo.full_name.replace('/', '_')}_{f.path}_{i}"
                        snippets.append(
                            WildSnippet(
                                snippet_id=sid,
                                source_tool=tool,
                                language=lang,
                                code=func,
                                repo_full_name=repo.full_name,
                                file_path=f.path,
                                commit_sha=repo.get_commits()[0].sha,
                            )
                        )
                except Exception:
                    continue
        except GithubException:
            pass
        return snippets

    @staticmethod
    def _detect_language(path: str) -> Optional[str]:
        for lang, exts in LANGUAGE_EXTENSIONS.items():
            if any(path.endswith(ext) for ext in exts):
                return lang
        return None

    @staticmethod
    def _extract_functions(code: str, language: str) -> List[str]:
        """Extract individual function/method bodies from source code."""
        functions: List[str] = []
        if language == "python":
            pattern = re.compile(
                r"(def\s+\w+\s*\(.*?\).*?:(?:\n(?:    |\t).+)+)",
                re.MULTILINE,
            )
        elif language == "javascript":
            pattern = re.compile(
                r"((?:function\s+\w+|const\s+\w+\s*=\s*(?:async\s*)?\(.*?\)\s*=>)\s*\{[^}]*\})",
                re.DOTALL,
            )
        elif language == "java":
            pattern = re.compile(
                r"((?:public|private|protected)\s+\w+\s+\w+\s*\([^)]*\)\s*\{[^}]*\})",
                re.DOTALL,
            )
        else:
            return [code[:2000]]

        for match in pattern.finditer(code):
            fn = match.group(1)
            if 20 <= len(fn) <= 3000:
                functions.append(fn)
        return functions
